Repository niolabs/nio-cli, pull requests merged in 2018-09, with the labels that each got.

#119 Ability to overwrite users on new
  nio_cli/commands/new.py
  nio_cli/utils.py
  tests/test_cli.py
Labels: change/change

#120 No username/password on config project
  nio_cli/commands/config.py
  nio_cli/utils.py
  tests/test_config.py
Labels: change/fixed

#121 Split out utils and use cryptography library
  nio_cli/cli.py
  nio_cli/commands/config.py
  nio_cli/commands/new.py
  nio_cli/utils.py
  nio_cli/utils/__init__.py
  nio_cli/utils/files.py
  nio_cli/utils/inputs.py
  nio_cli/utils/project.py
  nio_cli/utils/ssl.py
  nio_cli/utils/users.py
  setup.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_ssl.py
Labels: change/security

#124 Allow users to provide full instance host for access
  nio_cli/cli.py
  nio_cli/commands/base.py
  tests/test_cli.py
Labels: change/change, change/deprecated
