Repository niolabs/nio-cli, pull requests merged in 2018-08, with the labels that each got.

#112 NIO 1129
  .github/pull_request_template.md
  nio_cli/cli.py
  nio_cli/commands/base.py
  nio_cli/commands/config.py
  nio_cli/commands/new.py
  nio_cli/utils.py
  tests/test_cli.py
  tests/test_config.py
Labels: change/change

#113 fix options reference to pk host/port in config
  nio_cli/commands/config.py
Labels: change/fixed

#115 Use correct localhost ip
  nio_cli/commands/base.py
Labels: change/fixed

#114 Unshallow clone
  nio_cli/commands/new.py
  nio_cli/commands/newblock.py
  tests/test_cli.py
Labels: change/fixed

#118 add ssl flag to config
  nio_cli/cli.py
Labels: change/added

#117 Use bcrypt hashing for user/pasword creation
  nio_cli/utils.py
  setup.py
  tests/test_cli.py
Labels: change/security
